version: '3'
services:
  db:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
 mysql-volume:
